"""1

Revision ID: 125f0efced5a
Revises: 
Create Date: 2024-07-21 09:04:03.949962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125f0efced5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pendaftar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('no_telp', sa.String(length=64), nullable=True),
    sa.Column('bukti_transfer', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pendaftar')
    # ### end Alembic commands ###
